[tool.poetry]
name = "bender"
version = "0.1.6"
description = "cli tool"
authors = ["Charles Moreland <morelanc@ohsu.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.1"
requests = "^2.23.0"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"

[tool.poetry.scripts]
bender = 'bender.cli:cli'
jbender = 'bender.jira.cli:jira_cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
